<?php
include 'db.php';
@oci_execute(oci_parse($conn, "DROP TABLE PASSPORT CASCADE CONSTRAINTS"));
@oci_execute(oci_parse($conn, "DROP TABLE VERIFICATION CASCADE CONSTRAINTS"));
@oci_execute(oci_parse($conn, "DROP TABLE PAYMENT CASCADE CONSTRAINTS"));
@oci_execute(oci_parse($conn, "DROP TABLE PASSPORT_APPLICATION CASCADE CONSTRAINTS"));
@oci_execute(oci_parse($conn, "DROP TABLE APPLICANT CASCADE CONSTRAINTS"));
oci_execute(oci_parse($conn, "
CREATE TABLE APPLICANT (
    APPLICANT_ID VARCHAR2(10) PRIMARY KEY,
    NAME VARCHAR2(50)
)
"));
oci_execute(oci_parse($conn, "
CREATE TABLE PASSPORT_APPLICATION (
    APPLICATION_ID VARCHAR2(10) PRIMARY KEY,
    APPLICANT_ID VARCHAR2(10),
    TYPE VARCHAR2(20),
    FOREIGN KEY (APPLICANT_ID) REFERENCES APPLICANT(APPLICANT_ID) ON DELETE CASCADE
)
"));
oci_execute(oci_parse($conn, "
CREATE TABLE PAYMENT (
    PAYMENT_ID VARCHAR2(10) PRIMARY KEY,
    APPLICATION_ID VARCHAR2(10),
    AMOUNT NUMBER,
    FOREIGN KEY (APPLICATION_ID) REFERENCES PASSPORT_APPLICATION(APPLICATION_ID) ON DELETE CASCADE
)
"));
oci_execute(oci_parse($conn, "
CREATE TABLE VERIFICATION (
    VERIFICATION_ID VARCHAR2(10) PRIMARY KEY,
    APPLICATION_ID VARCHAR2(10),
    STATUS VARCHAR2(20),
    FOREIGN KEY (APPLICATION_ID) REFERENCES PASSPORT_APPLICATION(APPLICATION_ID) ON DELETE CASCADE
)
"));
oci_execute(oci_parse($conn, "
CREATE TABLE PASSPORT (
    PASSPORT_ID VARCHAR2(10) PRIMARY KEY,
    APPLICANT_ID VARCHAR2(10),
    STATUS VARCHAR2(20),
    FOREIGN KEY (APPLICANT_ID) REFERENCES APPLICANT(APPLICANT_ID) ON DELETE CASCADE
)
"));
echo "Setup Done with Cascade!";
?>